name: Deploy Lambda with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/lambdas/create_url/requirements.txt

    - name: Build Lambda package
      run: bash build.sh

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Initialize Terraform
      run: terraform init
      working-directory: infra

    - name: Import existing resources
      run: |
        terraform import aws_iam_role.lambda_exec_role lambda-url-shortener-role
        terraform import aws_dynamodb_table.url_shortener url-shortener-table
        terraform import aws_lambda_function.create_url_shortener create-url-shortener
      working-directory: infra
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1

    - name: Plan Terraform
      run: terraform plan -out=tfplan
      working-directory: infra
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1

    - name: Apply Terraform
      run: terraform apply -auto-approve tfplan
      working-directory: infra
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1